L: 32
M_omega: 30.0
M_phi: 30.0
T: 0.1
bell_mode: anti
bell_pin: true
cfgdir: cfg_md
dt: 5.0e-05
flip_every: 0
flip_mode: metropolis
gamma: 0.5
gauge_phi: false
kappa: 5000.0
quantum_flip: false
r_cut: 1.7
seed: 1234
sigma: 0.05
ticks: 20000
tunnel_alpha: 1.0
tunnel_delta: 1.0
